<a href="https://colab.research.google.com/github/shveta022-ks/Employee-exit-insights-dashboard/blob/main/Customers_clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd

In [6]:
df = pd.read_csv("/content/customers_unclean.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/content/customers_unclean.csv'

In [7]:
df.head(25)

,customer_id,customer_name,email,city,state
0,1,Amit Patel,AMIT.PATEL@GMAIL.COM,Bangalore,Karnataka
1,2,Amit Kapoor,AMIT.KAPOOR@GMAIL.COM,pune,Tamil Nadu
2,3,Rahul Verma,RAHUL.VERMA@GMAIL.COM,Jaipur,West Bengal
3,4,Sneha Kumar,NaN,Delhi,Rajasthan
4,5,Ishita Gupta,ishita.gupta@gmail.com,mumbai,Karnataka
5,6,Rohan Joshi,rohan.joshi@gmail.com,Ahmedabad,Gujarat
6,7,Vihaan Kapoor,vihaan.kapoor@gmail.com,Chennai,Karnataka
7,8,Aarav Iyer,aarav.iyer@gmail.com,Mumbai,Karnataka
8,9,Neha Kumar,neha.kumar@gmail.com,Delhi,Tamil Nadu
9,10,Amit Kumar,amit.kumar@gmail.com,Mumbai,Delhi
10,11,Rahul Singh,rahul.singh@gmail.com,Jaipur,Rajasthan
11,12,Meera Sharma,NaN,Chennai,Karnataka
12,13,Ananya Verma,ananya.verma@gmail.com,Ahmedabad,West Bengal
13,14,Aditya Kumar,aditya.kumar@gmail.com,Jaipur,Gujarat
14,15,Nikhil Verma,nikhil.verma@gmail.com,Delhi,Karnataka
15,16,Karan Sharma,karan.sharma@gmail.com,Delhi,Gujarat
16,17,Sneha Patel,sneha.patel@gmail.com,Ahmedabad,Maharashtra
17,18,Amit Patel,amit.patel@gmail.com,Hyderabad,Rajasthan
18,19,Vihaan Kumar,vihaan.kumar@gmail.com,Hyderabad,Delhi
19,20,Rahul Patel,rahul.patel@gmail.com,Jaipur,Delhi
20,21,Rohan Gupta,rohan.gupta@gmail.com,Jaipur,Rajasthan
21,22,Priya Sharma,priya.sharma@gmail.com,Hyderabad,Tamil Nadu
22,23,Nikhil Verma,nikhil.verma@gmail.com,Ahmedabad,Delhi
23,24,Aditya Iyer,aditya.iyer@gmail.com,Hyderabad,Gujarat
24,25,Ananya Kapoor,ananya.kapoor@gmail.com,Hyderabad,Rajasthan

In [9]:
df.tail(10)

,customer_id,customer_name,email,city,state
5190,682,Ananya Reddy,ananya.reddy@gmail.com,Kolkata,Delhi
5191,3795,Ishita Kumar,ishita.kumar@gmail.com,Pune,Karnataka
5192,3945,Ananya Kapoor,ananya.kapoor@gmail.com,Mumbai,West Bengal
5193,4667,Aarav Gupta,aarav.gupta@gmail.com,Delhi,West Bengal
5194,2019,Sneha Gupta,sneha.gupta@gmail.com,Pune,Karnataka
5195,1097,Ishita Verma,ishita.verma@gmail.com,chennai,Gujarat
5196,830,Sneha Singh,sneha.singh@gmail.com,Chennai,Maharashtra
5197,2806,Neha Singh,neha.singh@gmail.com,Mumbai,Gujarat
5198,3830,Neha Sharma,neha.sharma@gmail.com,mumbai,Rajasthan
5199,4382,Aarav Gupta,NaN,Bangalore,Telangana

In [7]:
df.info()

NameError: name 'df' is not defined

In [12]:
df.shape

(5200, 5)

In [13]:
df.columns

Index(['customer_id', 'customer_name', 'email', 'city', 'state'], dtype='object')

In [14]:
df.describe()

       customer_id
count  5200.000000
mean   2497.037115
std    1445.273612
min       1.000000
25%    1242.750000
50%    2499.500000
75%    3747.250000
max    5000.000000

In [18]:
df.isnull().sum()

customer_id      0
customer_name    0
email            0
city             0
state            0
dtype: int64

In [16]:
df['email'] = df['email'].fillna('unknown')

In [17]:
df.head(25)

,customer_id,customer_name,email,city,state
0,1,Amit Patel,AMIT.PATEL@GMAIL.COM,Bangalore,Karnataka
1,2,Amit Kapoor,AMIT.KAPOOR@GMAIL.COM,pune,Tamil Nadu
2,3,Rahul Verma,RAHUL.VERMA@GMAIL.COM,Jaipur,West Bengal
3,4,Sneha Kumar,unknown,Delhi,Rajasthan
4,5,Ishita Gupta,ishita.gupta@gmail.com,mumbai,Karnataka
5,6,Rohan Joshi,rohan.joshi@gmail.com,Ahmedabad,Gujarat
6,7,Vihaan Kapoor,vihaan.kapoor@gmail.com,Chennai,Karnataka
7,8,Aarav Iyer,aarav.iyer@gmail.com,Mumbai,Karnataka
8,9,Neha Kumar,neha.kumar@gmail.com,Delhi,Tamil Nadu
9,10,Amit Kumar,amit.kumar@gmail.com,Mumbai,Delhi
10,11,Rahul Singh,rahul.singh@gmail.com,Jaipur,Rajasthan
11,12,Meera Sharma,unknown,Chennai,Karnataka
12,13,Ananya Verma,ananya.verma@gmail.com,Ahmedabad,West Bengal
13,14,Aditya Kumar,aditya.kumar@gmail.com,Jaipur,Gujarat
14,15,Nikhil Verma,nikhil.verma@gmail.com,Delhi,Karnataka
15,16,Karan Sharma,karan.sharma@gmail.com,Delhi,Gujarat
16,17,Sneha Patel,sneha.patel@gmail.com,Ahmedabad,Maharashtra
17,18,Amit Patel,amit.patel@gmail.com,Hyderabad,Rajasthan
18,19,Vihaan Kumar,vihaan.kumar@gmail.com,Hyderabad,Delhi
19,20,Rahul Patel,rahul.patel@gmail.com,Jaipur,Delhi
20,21,Rohan Gupta,rohan.gupta@gmail.com,Jaipur,Rajasthan
21,22,Priya Sharma,priya.sharma@gmail.com,Hyderabad,Tamil Nadu
22,23,Nikhil Verma,nikhil.verma@gmail.com,Ahmedabad,Delhi
23,24,Aditya Iyer,aditya.iyer@gmail.com,Hyderabad,Gujarat
24,25,Ananya Kapoor,ananya.kapoor@gmail.com,Hyderabad,Rajasthan

In [19]:
df['city'] = df['city'].str.title()
df['state'] = df['state'].str.title()

In [20]:
df.head(25)

,customer_id,customer_name,email,city,state
0,1,Amit Patel,AMIT.PATEL@GMAIL.COM,Bangalore,Karnataka
1,2,Amit Kapoor,AMIT.KAPOOR@GMAIL.COM,Pune,Tamil Nadu
2,3,Rahul Verma,RAHUL.VERMA@GMAIL.COM,Jaipur,West Bengal
3,4,Sneha Kumar,unknown,Delhi,Rajasthan
4,5,Ishita Gupta,ishita.gupta@gmail.com,Mumbai,Karnataka
5,6,Rohan Joshi,rohan.joshi@gmail.com,Ahmedabad,Gujarat
6,7,Vihaan Kapoor,vihaan.kapoor@gmail.com,Chennai,Karnataka
7,8,Aarav Iyer,aarav.iyer@gmail.com,Mumbai,Karnataka
8,9,Neha Kumar,neha.kumar@gmail.com,Delhi,Tamil Nadu
9,10,Amit Kumar,amit.kumar@gmail.com,Mumbai,Delhi
10,11,Rahul Singh,rahul.singh@gmail.com,Jaipur,Rajasthan
11,12,Meera Sharma,unknown,Chennai,Karnataka
12,13,Ananya Verma,ananya.verma@gmail.com,Ahmedabad,West Bengal
13,14,Aditya Kumar,aditya.kumar@gmail.com,Jaipur,Gujarat
14,15,Nikhil Verma,nikhil.verma@gmail.com,Delhi,Karnataka
15,16,Karan Sharma,karan.sharma@gmail.com,Delhi,Gujarat
16,17,Sneha Patel,sneha.patel@gmail.com,Ahmedabad,Maharashtra
17,18,Amit Patel,amit.patel@gmail.com,Hyderabad,Rajasthan
18,19,Vihaan Kumar,vihaan.kumar@gmail.com,Hyderabad,Delhi
19,20,Rahul Patel,rahul.patel@gmail.com,Jaipur,Delhi
20,21,Rohan Gupta,rohan.gupta@gmail.com,Jaipur,Rajasthan
21,22,Priya Sharma,priya.sharma@gmail.com,Hyderabad,Tamil Nadu
22,23,Nikhil Verma,nikhil.verma@gmail.com,Ahmedabad,Delhi
23,24,Aditya Iyer,aditya.iyer@gmail.com,Hyderabad,Gujarat
24,25,Ananya Kapoor,ananya.kapoor@gmail.com,Hyderabad,Rajasthan

In [21]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

check duplicates.

In [24]:
df.reset_index(drop=True, inplace=True)

In [26]:
df.head(110)

,customer_id,customer_name,email,city,state
0,1,Amit Patel,AMIT.PATEL@GMAIL.COM,Bangalore,Karnataka
1,2,Amit Kapoor,AMIT.KAPOOR@GMAIL.COM,Pune,Tamil Nadu
2,3,Rahul Verma,RAHUL.VERMA@GMAIL.COM,Jaipur,West Bengal
3,4,Sneha Kumar,unknown,Delhi,Rajasthan
4,5,Ishita Gupta,ishita.gupta@gmail.com,Mumbai,Karnataka
...,...,...,...,...,...
105,106,Ishita Chopra,ishita.chopra@gmail.com,Ahmedabad,Maharashtra
106,107,Aditya Gupta,aditya.gupta@gmail.com,Mumbai,Karnataka
107,108,Rahul Reddy,rahul.reddy@gmail.com,Bangalore,Gujarat
108,109,Priya Chopra,priya.chopra@gmail.com,Kolkata,Maharashtra
109,110,Sneha Patel,sneha.patel@gmail.com,Bangalore,Karnataka

In [10]:
df.loc['city'] = df['city']

In [8]:
from google.colab import files
files.upload()

Saving customers_unclean.csv to customers_unclean.csv

{'customers_unclean.csv': b'customer_id,customer_name,email,city,state\n1,Amit Patel,AMIT.PATEL@GMAIL.COM,Bangalore,Karnataka\n2,Amit Kapoor,AMIT.KAPOOR@GMAIL.COM,pune,Tamil Nadu\n3,Rahul Verma,RAHUL.VERMA@GMAIL.COM,Jaipur,West Bengal\n4,Sneha Kumar,,Delhi,Rajasthan\n5,Ishita Gupta,ishita.gupta@gmail.com,mumbai,Karnataka\n6,Rohan Joshi,rohan.joshi@gmail.com,Ahmedabad,Gujarat\n7,Vihaan Kapoor,vihaan.kapoor@gmail.com,Chennai,Karnataka\n8,Aarav Iyer,aarav.iyer@gmail.com,Mumbai,Karnataka\n9,Neha Kumar,neha.kumar@gmail.com,Delhi,Tamil Nadu\n10,Amit Kumar,amit.kumar@gmail.com,Mumbai,Delhi\n11,Rahul Singh,rahul.singh@gmail.com,Jaipur,Rajasthan\n12,Meera Sharma,,Chennai,Karnataka\n13,Ananya Verma,ananya.verma@gmail.com,Ahmedabad,West Bengal\n14,Aditya Kumar,aditya.kumar@gmail.com,Jaipur,Gujarat\n15,Nikhil Verma,nikhil.verma@gmail.com,Delhi,Karnataka\n16,Karan Sharma,karan.sharma@gmail.com,Delhi,Gujarat\n17,Sneha Patel,sneha.patel@gmail.com,Ahmedabad,Maharashtra\n18,Amit Patel,amit.patel@gmail.com,Hyderabad,Rajasthan\n19,Vihaan Kumar,vihaan.kumar@gmail.com,Hyderabad,Delhi\n20,Rahul Patel,rahul.patel@gmail.com,Jaipur,Delhi\n21,Rohan Gupta,rohan.gupta@gmail.com,Jaipur,Rajasthan\n22,Priya Sharma,priya.sharma@gmail.com,Hyderabad,Tamil Nadu\n23,Nikhil Verma,nikhil.verma@gmail.com,Ahmedabad,Delhi\n24,Aditya Iyer,aditya.iyer@gmail.com,Hyderabad,Gujarat\n25,Ananya Kapoor,ananya.kapoor@gmail.com,Hyderabad,Rajasthan\n26,Priya Kapoor,priya.kapoor@gmail.com,Mumbai,Tamil Nadu\n27,Sneha Singh,SNEHA.SINGH@GMAIL.COM,Pune,Maharashtra\n28,Meera Joshi,MEERA.JOSHI@GMAIL.COM,Ahmedabad,Delhi\n29,Pooja Verma,pooja.verma@gmail.com,Ahmedabad,Tamil Nadu\n30,Vihaan Patel,vihaan.patel@gmail.com,Kolkata,Maharashtra\n31,Amit Iyer,amit.iyer@gmail.com,Kolkata,Karnataka\n32,Ananya Singh,ananya.singh@gmail.com,Kolkata,West Bengal\n33,Ananya Patel,ananya.patel@gmail.com,jaipur,Maharashtra\n34,Vihaan Singh,vihaan.singh@gmail.com,Bangalore,Maharashtra\n35,Aditya Reddy,ADITYA.REDDY@GMAIL.COM,Ahmedabad,West Bengal\n36,Aditya Singh,aditya.singh@gmail.com,jaipur,Rajasthan\n37,Aarav Sharma,aarav.sharma@gmail.com,Jaipur,Karnataka\n38,Meera Gupta,MEERA.GUPTA@GMAIL.COM,Bangalore,Tamil Nadu\n39,Sneha Verma,SNEHA.VERMA@GMAIL.COM,Jaipur,Telangana\n40,Ananya Iyer,ananya.iyer@gmail.com,Kolkata,Telangana\n41,Priya Joshi,priya.joshi@gmail.com,Pune,Karnataka\n42,Vihaan Kapoor,vihaan.kapoor@gmail.com,Chennai,Tamil Nadu\n43,Rohan Kumar,rohan.kumar@gmail.com,Hyderabad,Maharashtra\n44,Amit Kapoor,amit.kapoor@gmail.com,Delhi,Karnataka\n45,Pooja Kapoor,pooja.kapoor@gmail.com,Bangalore,Tamil Nadu\n46,Amit Iyer,amit.iyer@gmail.com,Hyderabad,Maharashtra\n47,Vihaan Iyer,vihaan.iyer@gmail.com,Pune,Delhi\n48,Amit Kumar,amit.kumar@gmail.com,Kolkata,Karnataka\n49,Vihaan Gupta,vihaan.gupta@gmail.com,Jaipur,Delhi\n50,Aarav Kumar,aarav.kumar@gmail.com,Pune,Tamil Nadu\n51,Amit Singh,amit.singh@gmail.com,Jaipur,Gujarat\n52,Sneha Gupta,sneha.gupta@gmail.com,Delhi,Delhi\n53,Nikhil Reddy,NIKHIL.REDDY@GMAIL.COM,Chennai,Gujarat\n54,Karan Iyer,karan.iyer@gmail.com,Hyderabad,Karnataka\n55,Neha Sharma,neha.sharma@gmail.com,Ahmedabad,Tamil Nadu\n56,Ananya Sharma,ananya.sharma@gmail.com,Hyderabad,Telangana\n57,Rohan Iyer,rohan.iyer@gmail.com,Jaipur,Maharashtra\n58,Vihaan Kumar,vihaan.kumar@gmail.com,hyderabad,Gujarat\n59,Rohan Joshi,rohan.joshi@gmail.com,Mumbai,Tamil Nadu\n60,Ishita Sharma,,Jaipur,Tamil Nadu\n61,Rohan Reddy,ROHAN.REDDY@GMAIL.COM,Chennai,Karnataka\n62,Pooja Kumar,pooja.kumar@gmail.com,Chennai,Telangana\n63,Rahul Gupta,rahul.gupta@gmail.com,Kolkata,Delhi\n64,Sneha Verma,sneha.verma@gmail.com,Pune,Tamil Nadu\n65,Neha Verma,neha.verma@gmail.com,Ahmedabad,Tamil Nadu\n66,Rahul Chopra,rahul.chopra@gmail.com,Delhi,Telangana\n67,Rahul Iyer,rahul.iyer@gmail.com,Bangalore,Tamil Nadu\n68,Karan Singh,,Ahmedabad,Karnataka\n69,Priya Reddy,priya.reddy@gmail.com,Kolkata,Tamil Nadu\n70,Aditya Iyer,aditya.iyer@gmail.com,Mumbai,Tamil Nadu\n71,Aditya Kapoor,aditya.kapoor@gmail.com,Mumbai,West Bengal\n72,Amit Kapoor,amit.kapoor@gmail.com,Ahmedabad,Gujarat\n73,Meera Kapoor,meera.kapoor@gmail.com,Ahmedabad,Tamil Nadu\n74,Meera Iyer,meera.iyer@gmail.com,Ahmedabad,Telangana\n75,Priya Patel,priya.patel@gmail.com,Chennai,Karnataka\n76,Aditya Gupta,aditya.gupta@gmail.com,bangalore,Gujarat\n77,Rohan Kapoor,rohan.kapoor@gmail.com,Kolkata,Maharashtra\n78,Meera Verma,,Chennai,Gujarat\n79,Meera Reddy,meera.reddy@gmail.com,Bangalore,Telangana\n80,Neha Chopra,NEHA.CHOPRA@GMAIL.COM,Kolkata,West Bengal\n81,Nikhil Gupta,nikhil.gupta@gmail.com,Kolkata,Maharashtra\n82,Vihaan Iyer,vihaan.iyer@gmail.com,delhi,Gujarat\n83,Rohan Singh,rohan.singh@gmail.com,Kolkata,Gujarat\n84,Ishita Patel,ishita.patel@gmail.com,Pune,Rajasthan\n85,Ananya Iyer,ANANYA.IYER@GMAIL.COM,Pune,Tamil Nadu\n86,Ananya Sharma,ananya.sharma@gmail.com,Ahmedabad,Tamil Nadu\n87,Priya Kumar,priya.kumar@gmail.com,Mumbai,Delhi\n88,Ishita Patel,ishita.patel@gmail.com,Kolkata,Tamil Nadu\n89,Vihaan Verma,vihaan.verma@gmail.com,Mumbai,Telangana\n90,Meera Iyer,meera.iyer@gmail.com,Pune,Gujarat\n91,Amit Joshi,AMIT.JOSHI@GMAIL.COM,Pune,West Bengal\n92,Vihaan Reddy,vihaan.reddy@gmail.com,Ahmedabad,Gujarat\n93,Aditya Kapoor,aditya.kapoor@gmail.com,Jaipur,West Bengal\n94,Neha Verma,neha.verma@gmail.com,Mumbai,West Bengal\n95,Ananya Chopra,ananya.chopra@gmail.com,chennai,Rajasthan\n96,Aditya Chopra,aditya.chopra@gmail.com,Chennai,Telangana\n97,Rahul Sharma,rahul.sharma@gmail.com,Bangalore,West Bengal\n98,Rahul Singh,rahul.singh@gmail.com,Ahmedabad,Maharashtra\n99,Vihaan Kumar,vihaan.kumar@gmail.com,Hyderabad,Rajasthan\n100,Priya Kapoor,priya.kapoor@gmail.com,Jaipur,West Bengal\n101,Ishita Kumar,ishita.kumar@gmail.com,Bangalore,Delhi\n102,Ananya Singh,ananya.singh@gmail.com,Jaipur,Karnataka\n103,Meera Singh,meera.singh@gmail.com,hyderabad,Delhi\n104,Ishita Sharma,ishita.sharma@gmail.com,Delhi,West Bengal\n105,Vihaan Sharma,vihaan.sharma@gmail.com,Ahmedabad,Maharashtra\n106,Ishita Chopra,ishita.chopra@gmail.com,ahmedabad,Maharashtra\n107,Aditya Gupta,aditya.gupta@gmail.com,Mumbai,Karnataka\n108,Rahul Reddy,rahul.reddy@gmail.com,Bangalore,Gujarat\n109,Priya Chopra,priya.chopra@gmail.com,Kolkata,Maharashtra\n110,Sneha Patel,sneha.patel@gmail.com,Bangalore,Karnataka\n111,Aditya Singh,aditya.singh@gmail.com,Pune,West Bengal\n112,Ishita Sharma,ishita.sharma@gmail.com,ahmedabad,Tamil Nadu\n113,Nikhil Kumar,nikhil.kumar@gmail.com,Bangalore,Tamil Nadu\n114,Amit Gupta,amit.gupta@gmail.com,mumbai,Telangana\n115,Sneha Verma,sneha.verma@gmail.com,Ahmedabad,Gujarat\n116,Ishita Kapoor,ishita.kapoor@gmail.com,Pune,Rajasthan\n117,Sneha Kumar,SNEHA.KUMAR@GMAIL.COM,Pune,Telangana\n118,Sneha Sharma,sneha.sharma@gmail.com,Jaipur,Telangana\n119,Aditya Verma,aditya.verma@gmail.com,Mumbai,Gujarat\n120,Rohan Joshi,rohan.joshi@gmail.com,Chennai,West Bengal\n121,Ishita Iyer,ishita.iyer@gmail.com,jaipur,Karnataka\n122,Rohan Kumar,rohan.kumar@gmail.com,Kolkata,Maharashtra\n123,Amit Kapoor,amit.kapoor@gmail.com,Jaipur,West Bengal\n124,Amit Chopra,amit.chopra@gmail.com,Jaipur,Telangana\n125,Priya Chopra,priya.chopra@gmail.com,Bangalore,Telangana\n126,Rahul Sharma,rahul.sharma@gmail.com,Mumbai,Karnataka\n127,Amit Gupta,amit.gupta@gmail.com,Jaipur,Gujarat\n128,Meera Chopra,meera.chopra@gmail.com,Jaipur,Tamil Nadu\n129,Nikhil Verma,nikhil.verma@gmail.com,Mumbai,Gujarat\n130,Rohan Kapoor,,Hyderabad,West Bengal\n131,Meera Gupta,meera.gupta@gmail.com,Chennai,Gujarat\n132,Priya Joshi,priya.joshi@gmail.com,Bangalore,Tamil Nadu\n133,Meera Reddy,MEERA.REDDY@GMAIL.COM,Kolkata,Delhi\n134,Priya Sharma,priya.sharma@gmail.com,Chennai,West Bengal\n135,Vihaan Kapoor,,Delhi,Delhi\n136,Vihaan Chopra,vihaan.chopra@gmail.com,Kolkata,Rajasthan\n137,Meera Iyer,meera.iyer@gmail.com,Chennai,West Bengal\n138,Meera Kapoor,MEERA.KAPOOR@GMAIL.COM,Hyderabad,Karnataka\n139,Neha Patel,neha.patel@gmail.com,Mumbai,Telangana\n140,Nikhil Sharma,NIKHIL.SHARMA@GMAIL.COM,Hyderabad,Gujarat\n141,Aditya Singh,aditya.singh@gmail.com,Delhi,Karnataka\n142,Sneha Reddy,sneha.reddy@gmail.com,Delhi,Telangana\n143,Priya Kumar,priya.kumar@gmail.com,Ahmedabad,Delhi\n144,Vihaan Chopra,vihaan.chopra@gmail.com,Hyderabad,Gujarat\n145,Pooja Kumar,pooja.kumar@gmail.com,Kolkata,Karnataka\n146,Ananya Reddy,ananya.reddy@gmail.com,hyderabad,Gujarat\n147,Ishita Sharma,ishita.sharma@gmail.com,Pune,West Bengal\n148,Meera Kumar,meera.kumar@gmail.com,Chennai,Tamil Nadu\n149,Sneha Kumar,sneha.kumar@gmail.com,Delhi,Maharashtra\n150,Ishita Chopra,ISHITA.CHOPRA@GMAIL.COM,delhi,Telangana\n151,Rohan Reddy,rohan.reddy@gmail.com,Jaipur,Rajasthan\n152,Rahul Kapoor,rahul.kapoor@gmail.com,Hyderabad,West Bengal\n153,Karan Kumar,karan.kumar@gmail.com,Mumbai,Karnataka\n154,Aditya Singh,aditya.singh@gmail.com,Kolkata,Rajasthan\n155,Vihaan Reddy,VIHAAN.REDDY@GMAIL.COM,Ahmedabad,Telangana\n156,Sneha Reddy,sneha.reddy@gmail.com,Mumbai,West Bengal\n157,Aarav Verma,aarav.verma@gmail.com,Bangalore,West Bengal\n158,Nikhil Kumar,nikhil.kumar@gmail.com,Pune,Telangana\n159,Priya Patel,PRIYA.PATEL@GMAIL.COM,Delhi,Rajasthan\n160,Amit Kapoor,amit.kapoor@gmail.com,Delhi,Karnataka\n161,Meera Chopra,meera.chopra@gmail.com,hyderabad,Rajasthan\n162,Ananya Chopra,ananya.chopra@gmail.com,chennai,Rajasthan\n163,Rahul Iyer,rahul.iyer@gmail.com,Bangalore,West Bengal\n164,Vihaan Iyer,vihaan.iyer@gmail.com,pune,Rajasthan\n165,Ananya Gupta,ananya.gupta@gmail.com,Jaipur,Tamil Nadu\n166,Meera Singh,meera.singh@gmail.com,Pune,Delhi\n167,Aditya Kapoor,aditya.kapoor@gmail.com,Pune,Rajasthan\n168,Karan Singh,,hyderabad,Gujarat\n169,Rahul Patel,rahul.patel@gmail.com,Chennai,Karnataka\n170,Priya Kapoor,priya.kapoor@gmail.com,Jaipur,Maharashtra\n171,Aarav Chopra,aarav.chopra@gmail.com,Mumbai,West Bengal\n172,Vihaan Patel,vihaan.patel@gmail.com,Delhi,Rajasthan\n173,Neha Verma,neha.verma@gmail.com,kolkata,Karnataka\n174,Meera Iyer,meera.iyer@gmail.com,Bangalore,Tamil Nadu\n175,Neha Joshi,neha.joshi@gmail.com,Mumbai,Rajasthan\n176,Amit Kumar,amit.kumar@gmail.com,ahmedabad,Karnataka\n177,Vihaan Reddy,VIHAAN.REDDY@GMAIL.COM,Delhi,Rajasthan\n178,Amit Patel,amit.patel@gmail.com,Kolkata,Maharashtra\n179,Ishita Verma,ishita.verma@gmail.com,Jaipur,West Bengal\n180,Ananya Patel,ananya.patel@gmail.com,Mumbai,Tamil Nadu\n181,Karan Reddy,karan.reddy@gmail.com,jaipur,Telangana\n182,Aarav Gupta,aarav.gupta@gmail.com,Chennai,Delhi\n183,Meera Gupta,meera.gupta@gmail.com,Delhi,Maharashtra\n184,Vihaan Kapoor,vihaan.kapoor@gmail.com,Chennai,Telangana\n185,Pooja Joshi,pooja.joshi@gmail.com,Mumbai,Delhi\n186,Aditya Verma,ADITYA.VERMA@GMAIL.COM,Ahmedabad,West Bengal\n187,Sneha Chopra,sneha.chopra@gmail.com,Jaipur,Gujarat\n188,Vihaan Kumar,vihaan.kumar@gmail.com,Jaipur,Maharashtra\n189,Ananya Reddy,ananya.reddy@gmail.com,Bangalore,Tamil Nadu\n190,Karan Gupta,karan.gupta@gmail.com,mumbai,Gujarat\n191,Aditya Gupta,aditya.gupta@gmail.com,Jaipur,Rajasthan\n192,Vihaan Reddy,,Pune,Karnataka\n193,Meera Joshi,meera.joshi@gmail.com,Kolkata,Gujarat\n194,Aarav Joshi,aarav.joshi@gmail.com,Ahmedabad,Rajasthan\n195,Vihaan Reddy,vihaan.reddy@gmail.com,Kolkata,Gujarat\n196,Meera Kumar,meera.kumar@gmail.com,delhi,Karnataka\n197,Rahul Kapoor,rahul.kapoor@gmail.com,Chennai,Delhi\n198,Ananya Patel,ananya.patel@gmail.com,Delhi,Karnataka\n199,Aditya Iyer,aditya.iyer@gmail.com,Ahmedabad,Rajasthan\n200,Meera Iyer,meera.iyer@gmail.com,Ahmedabad,Telangana\n201,Karan Kumar,karan.kumar@gmail.com,Mumbai,West Bengal\n202,Aarav Sharma,aarav.sharma@gmail.com,Mumbai,Gujarat\n203,Priya Verma,priya.verma@gmail.com,Pune,Tamil Nadu\n204,Rohan Verma,rohan.verma@gmail.com,Pune,Rajasthan\n205,Pooja Patel,pooja.patel@gmail.com,Bangalore,West Bengal\n206,Rahul Kapoor,rahul.kapoor@gmail.com,Hyderabad,Rajasthan\n207,Amit Verma,AMIT.VERMA@GMAIL.COM,chennai,Karnataka\n208,Rahul Iyer,rahul.iyer@gmail.com,Delhi,Delhi\n209,Nikhil Joshi,nikhil.joshi@gmail.com,Kolkata,Karnataka\n210,Ishita Kapoor,ishita.kapoor@gmail.com,Delhi,Karnataka\n211,Amit Iyer,amit.iyer@gmail.com,Chennai,Tamil Nadu\n212,Rohan Chopra,rohan.chopra@gmail.com,delhi,Karnataka\n213,Rahul Kapoor,rahul.kapoor@gmail.com,Pune,Delhi\n214,Sneha Reddy,sneha.reddy@gmail.com,Delhi,Maharashtra\n215,Neha Joshi,neha.joshi@gmail.com,Ahmedabad,West Bengal\n216,Ananya Kapoor,ananya.kapoor@gmail.com,Ahmedabad,Tamil Nadu\n217,Rohan Iyer,rohan.iyer@gmail.com,Ahmedabad,Gujarat\n218,Rahul Kapoor,rahul.kapoor@gmail.com,Bangalore,Delhi\n219,Meera Kumar,MEERA.KUMAR@GMAIL.COM,Chennai,Karnataka\n220,Pooja Kapoor,pooja.kapoor@gmail.com,Delhi,Delhi\n221,Meera Reddy,MEERA.REDDY@GMAIL.COM,Ahmedabad,Maharashtra\n222,Neha Sharma,neha.sharma@gmail.com,Kolkata,Rajasthan\n223,Ananya Sharma,ananya.sharma@gmail.com,Chennai,Delhi\n224,Aarav Kumar,aarav.kumar@gmail.com,Delhi,West Bengal\n225,Priya Verma,PRIYA.VERMA@GMAIL.COM,Hyderabad,Delhi\n226,Rahul Verma,rahul.verma@gmail.com,Hyderabad,Karnataka\n227,Aarav Singh,aarav.singh@gmail.com,ahmedabad,West Bengal\n228,Sneha Kapoor,SNEHA.KAPOOR@GMAIL.COM,Bangalore,Telangana\n229,Neha Sharma,neha.sharma@gmail.com,Kolkata,Karnataka\n230,Rahul Joshi,RAHUL.JOSHI@GMAIL.COM,Jaipur,Maharashtra\n231,Neha Chopra,NEHA.CHOPRA@GMAIL.COM,Chennai,Maharashtra\n232,Rohan Patel,rohan.patel@gmail.com,Mumbai,Rajasthan\n233,Aditya Sharma,aditya.sharma@gmail.com,Delhi,West Bengal\n234,Pooja Chopra,pooja.chopra@gmail.com,Mumbai,West Bengal\n235,Aarav Kumar,aarav.kumar@gmail.com,Pune,Telangana\n236,Rahul Reddy,rahul.reddy@gmail.com,hyderabad,Tamil Nadu\n237,Ishita Joshi,,Chennai,Rajasthan\n238,Neha Reddy,neha.reddy@gmail.com,Kolkata,Delhi\n239,Priya Chopra,priya.chopra@gmail.com,Hyderabad,Gujarat\n240,Vihaan Reddy,vihaan.reddy@gmail.com,Jaipur,Karnataka\n241,Vihaan Joshi,vihaan.joshi@gmail.com,Kolkata,West Bengal\n242,Rohan Chopra,ROHAN.CHOPRA@GMAIL.COM,Chennai,Gujarat\n243,Ishita Iyer,ishita.iyer@gmail.com,Mumbai,Gujarat\n244,Rohan Kapoor,rohan.kapoor@gmail.com,Pune,West Bengal\n245,Aarav Gupta,AARAV.GUPTA@GMAIL.COM,Chennai,Maharashtra\n246,Sneha Gupta,sneha.gupta@gmail.com,Chennai,Karnataka\n247,Sneha Gupta,sneha.gupta@gmail.com,Hyderabad,Karnataka\n248,Aarav Gupta,aarav.gupta@gmail.com,Jaipur,Telangana\n249,Pooja Chopra,pooja.chopra@gmail.com,Ahmedabad,Delhi\n250,Meera Patel,meera.patel@gmail.com,Ahmedabad,Rajasthan\n251,Amit Joshi,amit.joshi@gmail.com,Hyderabad,Delhi\n252,Pooja Iyer,pooja.iyer@gmail.com,Bangalore,Tamil Nadu\n253,Karan Gupta,karan.gupta@gmail.com,Chennai,Rajasthan\n254,Priya Kapoor,priya.kapoor@gmail.com,Mumbai,West Bengal\n255,Rahul Reddy,rahul.reddy@gmail.com,Mumbai,Rajasthan\n256,Amit Patel,amit.patel@gmail.com,Chennai,Delhi\n257,Karan Gupta,karan.gupta@gmail.com,Pune,Delhi\n258,Ishita Gupta,ishita.gupta@gmail.com,Bangalore,Telangana\n259,Meera Patel,meera.patel@gmail.com,Jaipur,Telangana\n260,Sneha Kapoor,SNEHA.KAPOOR@GMAIL.COM,Delhi,Rajasthan\n261,Meera Verma,MEERA.VERMA@GMAIL.COM,mumbai,Telangana\n262,Amit Singh,amit.singh@gmail.com,Pune,Telangana\n263,Amit Kumar,amit.kumar@gmail.com,Kolkata,Karnataka\n264,Pooja Sharma,pooja.sharma@gmail.com,Ahmedabad,Delhi\n265,Rohan Joshi,rohan.joshi@gmail.com,Kolkata,Rajasthan\n266,Rahul Kapoor,rahul.kapoor@gmail.com,Mumbai,Tamil Nadu\n267,Aditya Patel,ADITYA.PATEL@GMAIL.COM,Kolkata,Delhi\n268,Meera Joshi,meera.joshi@gmail.com,Bangalore,West Bengal\n269,Rahul Chopra,rahul.chopra@gmail.com,pune,Gujarat\n270,Rahul Chopra,rahul.chopra@gmail.com,chennai,Telangana\n271,Priya Verma,priya.verma@gmail.com,Ahmedabad,Maharashtra\n272,Meera Patel,meera.patel@gmail.com,Chennai,Rajasthan\n273,Aarav Reddy,AARAV.REDDY@GMAIL.COM,Chennai,Karnataka\n274,Neha Kapoor,neha.kapoor@gmail.com,Mumbai,Karnataka\n275,Neha Joshi,neha.joshi@gmail.com,Chennai,Tamil Nadu\n276,Sneha Kapoor,,Pune,Rajasthan\n277,Karan Chopra,karan.chopra@gmail.com,Jaipur,Rajasthan\n278,Aditya Reddy,aditya.reddy@gmail.com,Hyderabad,West Bengal\n279,Pooja Verma,pooja.verma@gmail.com,Chennai,Karnataka\n280,Neha Verma,neha.verma@gmail.com,Pune,Telangana\n281,Amit Verma,amit.verma@gmail.com,Ahmedabad,Gujarat\n282,Aditya Iyer,aditya.iyer@gmail.com,Mumbai,West Bengal\n283,Rohan Reddy,rohan.reddy@gmail.com,Kolkata,West Bengal\n284,Meera Sharma,meera.sharma@gmail.com,Jaipur,West Bengal\n285,Rahul Reddy,rahul.reddy@gmail.com,Jaipur,Rajasthan\n286,Amit Iyer,amit.iyer@gmail.com,Ahmedabad,Tamil Nadu\n287,Ishita Kapoor,ishita.kapoor@gmail.com,Hyderabad,Tamil Nadu\n288,Pooja Chopra,pooja.chopra@gmail.com,Hyderabad,Gujarat\n289,Nikhil Reddy,nikhil.reddy@gmail.com,Delhi,Telangana\n290,Pooja Patel,pooja.patel@gmail.com,Hyderabad,Tamil Nadu\n291,Ananya Kapoor,ananya.kapoor@gmail.com,Hyderabad,Tamil Nadu\n292,Ananya Sharma,ananya.sharma@gmail.com,bangalore,Gujarat\n293,Rohan Chopra,rohan.chopra@gmail.com,Pune,Delhi\n294,Neha Iyer,neha.iyer@gmail.com,Ahmedabad,Telangana\n295,Rohan Kumar,rohan.kumar@gmail.com,Mumbai,Tamil Nadu\n296,Rahul Sharma,rahul.sharma@gmail.com,Delhi,Maharashtra\n297,Meera Reddy,meera.reddy@gmail.com,Hyderabad,Maharashtra\n298,Ishita Verma,ishita.verma@gmail.com,Chennai,West Bengal\n299,Nikhil Gupta,nikhil.gupta@gmail.com,Bangalore,Rajasthan\n300,Aditya Chopra,aditya.chopra@gmail.com,Pune,Telangana\n301,Sneha Iyer,sneha.iyer@gmail.com,Kolkata,Rajasthan\n302,Vihaan Reddy,vihaan.reddy@gmail.com,Delhi,Tamil Nadu\n303,Aarav Kumar,aarav.kumar@gmail.com,Hyderabad,Telangana\n304,Sneha Verma,SNEHA.VERMA@GMAIL.COM,bangalore,Karnataka\n305,Priya Kumar,priya.kumar@gmail.com,Hyderabad,Telangana\n306,Rohan Verma,rohan.verma@gmail.com,Ahmedabad,Rajasthan\n307,Neha Kapoor,neha.kapoor@gmail.com,Bangalore,Karnataka\n308,Rahul Chopra,rahul.chopra@gmail.com,mumbai,Tamil Nadu\n309,Sneha Kapoor,sneha.kapoor@gmail.com,Jaipur,Tamil Nadu\n310,Pooja Verma,pooja.verma@gmail.com,Ahmedabad,West Bengal\n311,Aditya Kapoor,aditya.kapoor@gmail.com,Jaipur,Telangana\n312,Pooja Sharma,pooja.sharma@gmail.com,Bangalore,Maharashtra\n313,Neha Joshi,neha.joshi@gmail.com,Pune,Karnataka\n314,Nikhil Chopra,NIKHIL.CHOPRA@GMAIL.COM,Delhi,Gujarat\n315,Rohan Reddy,rohan.reddy@gmail.com,Kolkata,Delhi\n316,Amit Joshi,amit.joshi@gmail.com,Kolkata,Tamil Nadu\n317,Meera Sharma,meera.sharma@gmail.com,Ahmedabad,Gujarat\n318,Rahul Reddy,rahul.reddy@gmail.com,Chennai,Tamil Nadu\n319,Nikhil Patel,NIKHIL.PATEL@GMAIL.COM,Pune,Karnataka\n320,Vihaan Verma,VIHAAN.VERMA@GMAIL.COM,Pune,Maharashtra\n321,Neha Chopra,neha.chopra@gmail.com,Pune,Telangana\n322,Ananya Verma,ananya.verma@gmail.com,Chennai,Delhi\n323,Amit Kapoor,amit.kapoor@gmail.com,Pune,Delhi\n324,Amit Iyer,amit.iyer@gmail.com,Chennai,Gujarat\n325,Karan Kapoor,karan.kapoor@gmail.com,Delhi,Delhi\n326,Karan Kapoor,karan.kapoor@gmail.com,Hyderabad,Delhi\n327,Karan Chopra,karan.chopra@gmail.com,Kolkata,Delhi\n328,Neha Singh,neha.singh@gmail.com,Mumbai,Rajasthan\n329,Vihaan Kapoor,vihaan.kapoor@gmail.com,Hyderabad,Maharashtra\n330,Meera Patel,meera.patel@gmail.com,Jaipur,Tamil Nadu\n331,Meera Joshi,meera.joshi@gmail.com,Bangalore,Karnataka\n332,Pooja Chopra,pooja.chopra@gmail.com,Bangalore,Tamil Nadu\n333,Rahul Joshi,rahul.joshi@gmail.com,Jaipur,Telangana\n334,Ishita Joshi,ishita.joshi@gmail.com,Mumbai,West Bengal\n335,Karan Joshi,karan.joshi@gmail.com,kolkata,Tamil Nadu\n336,Pooja Gupta,POOJA.GUPTA@GMAIL.COM,Kolkata,Tamil Nadu\n337,Rohan Singh,rohan.singh@gmail.com,Ahmedabad,Rajasthan\n338,Ishita Chopra,ishita.chopra@gmail.com,Ahmedabad,Rajasthan\n339,Aditya Gupta,aditya.gupta@gmail.com,Jaipur,Maharashtra\n340,Rahul Sharma,rahul.sharma@gmail.com,Pune,Gujarat\n341,Aditya Iyer,aditya.iyer@gmail.com,Pune,West Bengal\n342,Rohan Sharma,rohan.sharma@gmail.com,Ahmedabad,Maharashtra\n343,Aarav Kapoor,,Jaipur,Telangana\n344,Aarav Kapoor,aarav.kapoor@gmail.com,Delhi,Karnataka\n345,Rahul Gupta,rahul.gupta@gmail.com,Hyderabad,Telangana\n346,Karan Reddy,KARAN.REDDY@GMAIL.COM,Ahmedabad,Tamil Nadu\n347,Ishita Iyer,ishita.iyer@gmail.com,pune,Gujarat\n348,Neha Kapoor,neha.kapoor@gmail.com,delhi,Gujarat\n349,Amit Joshi,amit.joshi@gmail.com,Mumbai,Maharashtra\n350,Ananya Singh,ananya.singh@gmail.com,Ahmedabad,Karnataka\n351,Amit Kumar,amit.kumar@gmail.com,Pune,Rajasthan\n352,Aarav Singh,aarav.singh@gmail.com,Kolkata,Telangana\n353,Aditya Verma,aditya.verma@

In [9]:
df = pd.read_csv("/content/customers_unclean.csv")

In [11]:
df.head(25)

,customer_id,customer_name,email,city,state
0,1.0,Amit Patel,AMIT.PATEL@GMAIL.COM,Bangalore,Karnataka
1,2.0,Amit Kapoor,AMIT.KAPOOR@GMAIL.COM,pune,Tamil Nadu
2,3.0,Rahul Verma,RAHUL.VERMA@GMAIL.COM,Jaipur,West Bengal
3,4.0,Sneha Kumar,NaN,Delhi,Rajasthan
4,5.0,Ishita Gupta,ishita.gupta@gmail.com,mumbai,Karnataka
5,6.0,Rohan Joshi,rohan.joshi@gmail.com,Ahmedabad,Gujarat
6,7.0,Vihaan Kapoor,vihaan.kapoor@gmail.com,Chennai,Karnataka
7,8.0,Aarav Iyer,aarav.iyer@gmail.com,Mumbai,Karnataka
8,9.0,Neha Kumar,neha.kumar@gmail.com,Delhi,Tamil Nadu
9,10.0,Amit Kumar,amit.kumar@gmail.com,Mumbai,Delhi
10,11.0,Rahul Singh,rahul.singh@gmail.com,Jaipur,Rajasthan
11,12.0,Meera Sharma,NaN,Chennai,Karnataka
12,13.0,Ananya Verma,ananya.verma@gmail.com,Ahmedabad,West Bengal
13,14.0,Aditya Kumar,aditya.kumar@gmail.com,Jaipur,Gujarat
14,15.0,Nikhil Verma,nikhil.verma@gmail.com,Delhi,Karnataka
15,16.0,Karan Sharma,karan.sharma@gmail.com,Delhi,Gujarat
16,17.0,Sneha Patel,sneha.patel@gmail.com,Ahmedabad,Maharashtra
17,18.0,Amit Patel,amit.patel@gmail.com,Hyderabad,Rajasthan
18,19.0,Vihaan Kumar,vihaan.kumar@gmail.com,Hyderabad,Delhi
19,20.0,Rahul Patel,rahul.patel@gmail.com,Jaipur,Delhi
20,21.0,Rohan Gupta,rohan.gupta@gmail.com,Jaipur,Rajasthan
21,22.0,Priya Sharma,priya.sharma@gmail.com,Hyderabad,Tamil Nadu
22,23.0,Nikhil Verma,nikhil.verma@gmail.com,Ahmedabad,Delhi
23,24.0,Aditya Iyer,aditya.iyer@gmail.com,Hyderabad,Gujarat
24,25.0,Ananya Kapoor,ananya.kapoor@gmail.com,Hyderabad,Rajasthan

In [12]:
df = pd.read_csv("/content/orders_unclean.csv")

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     25000 non-null  int64
 1   customer_id  25000 non-null  int64
 2   order_date   25000 non-null  object
 3   ship_mode    25000 non-null  object
 4   region       25000 non-null  object
dtypes: int64(2), object(3)
memory usage: 976.7+ KB

In [16]:
df.head(25)

    order_id  customer_id  order_date       ship_mode   region
0          1         1127  2019-02-25     First Class     West
1          2         4005  2019-01-24     First Class     East
2          3         4777  2021-04-03    Second Class  Central
3          4         2954  2019-03-09    Second Class     East
4          5         2534  2019-06-04  Standard Class     East
5          6         3473  2022-08-17        Same Day     East
6          7         1640  2021-01-18  Standard Class     East
7          8         3477  2020-10-09     First Class  Central
8          9          891  2021-04-18  Standard Class    South
9         10         1161  2020-07-07        Same Day  Central
10        11         2255  2021-12-29  Standard Class    South
11        12         3593  2020-03-05  Standard Class     East
12        13         4342  2021-04-02    Second Class    South
13        14         4374  2019-05-03     First Class    South
14        15         4756  2022-06-07  Standard Class  Central
15        16         1569  2020-01-10    Second Class     East
16        17         4548  2020-12-12  Standard Class     East
17        18         4188  2020-12-13     First Class     East
18        19         2731  2022-10-03    Second Class  Central
19        20          230  2020-11-19        Same Day    South
20        21         4073  2019-04-04     First Class     West
21        22         2955  2020-03-09  Standard Class    South
22        23         2934  2019-09-27    Second Class    South
23        24         3878  2022-12-12        Same Day     West
24        25         2074  2021-09-15  Standard Class    South

In [17]:
df.iloc[0:25,0:5]

    order_id  customer_id  order_date       ship_mode   region
0          1         1127  2019-02-25     First Class     West
1          2         4005  2019-01-24     First Class     East
2          3         4777  2021-04-03    Second Class  Central
3          4         2954  2019-03-09    Second Class     East
4          5         2534  2019-06-04  Standard Class     East
5          6         3473  2022-08-17        Same Day     East
6          7         1640  2021-01-18  Standard Class     East
7          8         3477  2020-10-09     First Class  Central
8          9          891  2021-04-18  Standard Class    South
9         10         1161  2020-07-07        Same Day  Central
10        11         2255  2021-12-29  Standard Class    South
11        12         3593  2020-03-05  Standard Class     East
12        13         4342  2021-04-02    Second Class    South
13        14         4374  2019-05-03     First Class    South
14        15         4756  2022-06-07  Standard Class  Central
15        16         1569  2020-01-10    Second Class     East
16        17         4548  2020-12-12  Standard Class     East
17        18         4188  2020-12-13     First Class     East
18        19         2731  2022-10-03    Second Class  Central
19        20          230  2020-11-19        Same Day    South
20        21         4073  2019-04-04     First Class     West
21        22         2955  2020-03-09  Standard Class    South
22        23         2934  2019-09-27    Second Class    South
23        24         3878  2022-12-12        Same Day     West
24        25         2074  2021-09-15  Standard Class    South